[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "postgresql"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip3 install -r requirements.txt"]

[phases.build]
cmds = ["python3 shoessite/manage.py collectstatic --noinput"]

[start]
cmd = "python3 shoessite/manage.py migrate && cd shoessite && gunicorn shoessite.wsgi:application --bind 0.0.0.0:$PORT"

